baseurl = "/"
languageCode = "en-us"
title = "Allen Sirolly"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "sirallen"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3
[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 4
#[[menu.main]]
#    name = "Projects"
#    url = "/projects/"
#    weight = 3
#[[menu.main]]
#    name = "Resources"
#    url = "/resources/"
#    weight = 4

[params]
    # description = "A website built with Hugo and blogdown."
    footer = "&copy; Allen Sirolly 2026 | [Github](https://github.com/sirallen) | [X (formerly Twitter)](https://twitter.com/allensirolly)"
    custom_css = ["css/custom.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "Sirolly_Allen.jpg"
    width = 140
    height = 140
    alt = "Allen Sirolly"