baseurl = "/"
languageCode = "en-us"
title = "Allen Sirolly"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "sirallen"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
#[[menu.main]]
#    name = "Resources"
#    url = "/resources/"
#    weight = 4

[params]
    # description = "A website built with Hugo and blogdown."
    footer = "&copy; Allen Sirolly 2017 | [Github](https://github.com/sirallen) | [Twitter](https://twitter.com/Sirallenrolly)"
    custom_css = ["css/custom.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.PNG"
    width = 50
    height = 50
    alt = "Logo"

